### ISSUE TITLE
Compatibility issues between owltools and Brain

### ISSUE THREAD

**Issue by dosumis** [dosumis/travis-jython-test#1]
Running with owltools (latest snapshot) + Brain (2.5.1) => 

``` .log
  File "call_brain.py", line 5, in <module>
    b.getSubClasses('Thing', 0)
    at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.<init>(ManchesterOWLSyntaxEditorParser.java:207)
    at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.<init>(ManchesterOWLSyntaxEditorParser.java:178)
    at uk.ac.ebi.brain.core.Brain.getParser(Brain.java:1315)
    at uk.ac.ebi.brain.core.Brain.parseClassExpression(Brain.java:1211)
    at uk.ac.ebi.brain.core.Brain.getSubClasses(Brain.java:1516)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
java.lang.NoSuchMethodError: java.lang.NoSuchMethodError: org.semanticweb.owlapi.vocab.XSDVocabulary.getPrefixedName()Ljava/lang/String;
```

Works when owltools dependency removed from pom.xml.

**Comment by dosumis** [comment]
Options:

Try with versions of Brain and OwlTools using closer versions of OWL-API.

Update Brain?
